version: '3'
services:
  recommendationsapi:
    container_name: recommendations-api-unstable
    ports:
    - 8082:8080
    image: recommendations-api:unstable
    build:
      context: ./recommendations-api
      dockerfile: Dockerfile
    environment:
      REDIS_URI: redis://recommendations-redis
  recommendations-redis:
    container_name: recommendations-redis
    image: redis:5
    ports:
    - 6379:6379
    volumes:
    - ./redis_volumes/rec_db:/data
  contentapi:
    container_name: content-api-unstable
    ports:
    - 8081:8080
    image: content-api:unstable
    build:
      context: ./content-api
      dockerfile: Dockerfile
    environment:
      REDIS_URI: redis://content-redis
  content-redis:
    container_name: content-redis
    image: redis:5
    ports:
    - 6380:6379
    volumes:
    - ./redis_volumes/content_db:/data
  # api-gateway-hystrix:
  #   container_name: api-gateway-hystrix
  #   build:
  #     context: ./api-gateway-hystrix
  #     dockerfile: Dockerfile
  #   ports:
  #   - 8083:8080
  hystrix-dashboard:
    container_name: hystrix-dashboard
    image: mlabouardy/hystrix-dashboard
    ports:
    - 9002:9002