---
micronaut:
    application:
        name: api-gateway
    server:
        port: 8080
    http:
        client:
            read-timeout: 1s
---
graphql:
    enabled: true
    path: /graphql
    graphiql:
        enabled: true
        path: /graphiql
        template-path: classpath:graphiql/index.html
        template-parameters:
        page-title: GraphiQL
---
jackson:
    deserialization:
        unwrapSingleValueArrays: true